### ISSUE TITLE
API method to execute raw SQL

### ISSUE THREAD

**Issue by acmk01** [quantmind/pulsar-odm#9]

**Comment by lsbardel** [comment]
@acmk01 it would be useful to have a test to cover this https://github.com/quantmind/pulsar-odm/commit/59fd058dc7def224c4ba74ce4446c591f0c91f33

No coverage
https://coveralls.io/builds/5044963/source?filename=odm%2Fmapper.py#L184

Maybe create a little table with sql in [test/__init__.py](https://github.com/quantmind/pulsar-odm/blob/master/tests/__init__.py)?
